openapi: 3.0.0

info:
  title: Simple Order API
  version: "1.0.0"
  description: This is a simple Order management API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://virtserver.swaggerhub.com/HOGANHFANG/online_order/1.0.0
    description: SwaggerHub API Auto Mocking

paths:

  /order:
    get:
      summary: Search order
      operationId: searchOrder
      description: Search order by reference
      parameters:
        - in: query
          name: reference
          description: Order reference (UUID)
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid reference (e.g. not a valid UUID)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidReferenceResponse'
        '404':
          description: Order not found

    post:
      summary: Create order
      operationId: createOrder
      description: Add a new order to the system
      requestBody:
        description: Order to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid input (e.g. invalid card) or order already exists, see reason
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderErrorResponse'

components:

  schemas:

    # =========================
    # Order Schemas
    # =========================

    OrderRequest:
      type: object
      required:
        - reference
        - name
        - products
        - callback
        - cardNumber
        - cvv
        - expiry
        - amount
        - currency
      properties:
        reference:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter Order
        callback:
          type: string
          format: uri
          example: http://www.xxx.com
        cardNumber:
          type: string
          description: 卡号
          example: "4111111111111111"
        cvv:
          type: string
          description: CVV
          example: "123"
        expiry:
          type: string
          description: 有效期，如 MM/YY
          example: "12/28"
        amount:
          type: number
          format: double
          description: 金额
          example: 99.99
        currency:
          type: string
          description: 币种，如 USD、CNY
          example: "USD"
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductRequest'

    OrderResponse:
      type: object
      description: 查询结果返回掩码卡号（前6后4），不包含CVV与有效期
      properties:
        reference:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        orderId:
          type: string
          format: string
          example: PX39280930012
        name:
          type: string
          example: Widget Adapter Order
        orderDate:
          type: string
          format: date-time
          example: 2024-01-10T10:15:30Z
        amount:
          type: number
          format: double
          description: 金额
          example: 99.99
        currency:
          type: string
          description: 币种
          example: "USD"
        status:
          type: string
          description: Order status (uppercase)
          enum: [PROCESSING, FAIL, COMPLETE]
          example: PROCESSING
        fail_reason:
          type: string
          description: 失败原因，仅 status 为 FAIL 时有值
          nullable: true
        cardNumber:
          type: string
          description: 掩码卡号（前6后4位可见）
          example: "555555******4444"
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'

    # GET /order 400: reference 非合法 UUID
    InvalidReferenceResponse:
      type: object
      required:
        - status
        - reason
      properties:
        status:
          type: string
          enum: [FAIL]
          example: FAIL
        reason:
          type: string
          example: "invalid UUID string"

    # 400: status、reason 与订单字段同层，无 detail/order 嵌套
    OrderErrorResponse:
      type: object
      required:
        - status
        - reason
      properties:
        status:
          type: string
          enum: [FAIL]
          example: FAIL
        reason:
          type: string
          example: Invalid card
        reference:
          type: string
          format: uuid
        orderId:
          type: string
        name:
          type: string
        orderDate:
          type: string
          format: date-time
        amount:
          type: number
        currency:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        cardNumber:
          type: string
          description: 仅 400 无效卡时可能返回

    # =========================
    # Product Schemas
    # =========================

    ProductBase:
      type: object
      required:
        - productId
        - count
        - spec
      properties:
        productId:
          type: string
          example: 29838-02
        count:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          example: 2
        spec:
          type: string
          example: xs-83

    ProductRequest:
      allOf:
        - $ref: '#/components/schemas/ProductBase'

    ProductResponse:
      allOf:
        - $ref: '#/components/schemas/ProductBase'
        - type: object
          properties:
            status:
              type: string
              description: Product status (uppercase: PENDING, SHIPPED, COMPLETE)
              example: SHIPPED
