openapi: 3.0.0

info:
  title: QWire Callback API v2
  version: "2.0.0"
  description: Callback receiving API with log-only query behavior
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://127.0.0.1:8100
    description: Local callback server

paths:
  /check:
    get:
      summary: Check order callback
      operationId: check
      description: Callback records are log-only and not queryable
      parameters:
        - in: query
          name: reference
          description: Order reference (UUID)
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '404':
          description: Callback records are log-only and not queryable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetailResponse'
        '422':
          description: Invalid UUID query parameter
  /callback:
    post:
      summary: Order status callback
      operationId: callback
      description: Receive callback from order system
      requestBody:
        description: Callback info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderResponse'
      responses:
        '200':
          description: Received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Received'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'

components:

  schemas:
    # =========================
    # Received Schemas
    # =========================
    Received:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          format: string
          example: OK

    ErrorDetailResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          example: Callback records are log-only and not queryable

    ValidationErrorResponse:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
          example: Invalid order payload
        errors:
          type: array
          items:
            type: object
            additionalProperties: true

    # =========================
    # Order Schemas
    # =========================

    OrderResponse:
      type: object
      description: Query/callback result returns a masked card number (first 6 and last 4 visible), without CVV and expiry
      required:
        - reference
        - orderId
        - name
        - orderDate
        - amount
        - currency
        - status
        - cardNumber
        - products
      properties:
        reference:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        orderId:
          type: string
          format: string
          example: PX39280930012
        name:
          type: string
          example: Widget Adapter Order
        orderDate:
          type: string
          format: date-time
          example: 2024-01-10T10:15:30Z
        amount:
          type: number
          format: double
          description: Amount
          example: 99.99
        currency:
          type: string
          description: Currency
          example: "USD"
        status:
          type: string
          description: Order status (uppercase)
          enum: [SUCCESS, COMPLETED, FAIL]
          example: SUCCESS
        fail_reason:
          type: string
          description: Failure reason, only present when status is FAIL
          nullable: true
        cardNumber:
          type: string
          description: Masked card number (first 6 and last 4 digits visible)
          example: "555555******4444"
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'

    # =========================
    # Product Schemas
    # =========================

    ProductBase:
      type: object
      required:
        - productId
        - count
        - spec
      properties:
        productId:
          type: string
          example: 29838-02
        count:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          example: 2
        spec:
          type: string
          example: xs-83

    ProductResponse:
      allOf:
        - $ref: '#/components/schemas/ProductBase'
        - type: object
          properties:
            status:
              type: string
              description: Product status (uppercase)
              enum: [PROCESSING, SHIPPED, DELIVERED, FAIL]
              example: PROCESSING
