openapi: 3.0.0

info:
  title: QWire Order API v2
  version: "2.0.0"
  description: Order create/query API with MySQL persistence and scheduled status transitions
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://127.0.0.1:9100
    description: Local order server

paths:

  /order:
    get:
      summary: Search order
      operationId: searchOrder
      description: Search order by reference
      parameters:
        - in: query
          name: reference
          description: Order reference (UUID)
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid reference (e.g. not a valid UUID)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderQueryErrorResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderQueryErrorResponse'

    post:
      summary: Create order
      operationId: createOrder
      description: Add a new order to the system
      requestBody:
        description: Order to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid input (e.g. unsupported card type) or order already exists
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/OrderResponse'
                  - $ref: '#/components/schemas/OrderCreateErrorResponse'

components:

  schemas:

    # =========================
    # Order Schemas
    # =========================

    OrderRequest:
      type: object
      required:
        - reference
        - name
        - products
        - callback
        - cardNumber
        - cvv
        - expiry
        - amount
        - currency
      properties:
        reference:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter Order
        callback:
          type: string
          format: uri
          example: http://www.xxx.com
        cardNumber:
          type: string
          description: Card number
          example: "4111111111111111"
        cvv:
          type: string
          description: CVV
          example: "123"
        expiry:
          type: string
          description: Expiry date, e.g. MM/YY
          example: "12/28"
        amount:
          type: number
          format: double
          description: Amount
          example: 99.99
        currency:
          type: string
          description: Currency, e.g. USD, CNY
          example: "USD"
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductRequest'

    OrderResponse:
      type: object
      description: Query result returns a masked card number (first 6 and last 4 visible), without CVV and expiry
      required:
        - reference
        - orderId
        - name
        - orderDate
        - amount
        - currency
        - status
        - cardNumber
        - products
      properties:
        reference:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        orderId:
          type: string
          format: string
          example: PX39280930012
        name:
          type: string
          example: Widget Adapter Order
        orderDate:
          type: string
          format: date-time
          example: 2024-01-10T10:15:30Z
        amount:
          type: number
          format: double
          description: Amount
          example: 99.99
        currency:
          type: string
          description: Currency
          example: "USD"
        status:
          type: string
          description: Order status (uppercase)
          enum: [SUCCESS, COMPLETED, FAIL]
          example: SUCCESS
        fail_reason:
          type: string
          description: Failure reason, only present when status is FAIL
          nullable: true
        cardNumber:
          type: string
          description: Masked card number (first 6 and last 4 visible)
          example: "555555******4444"
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'

    OrderQueryErrorResponse:
      type: object
      required:
        - status
        - fail_reason
        - reference
      properties:
        status:
          type: string
          enum: [FAIL]
          example: FAIL
        fail_reason:
          type: string
          example: "Order not found"
        reference:
          type: string
          description: Raw query value

    OrderCreateErrorResponse:
      type: object
      required:
        - status
        - fail_reason
      properties:
        status:
          type: string
          enum: [FAIL]
          example: FAIL
        fail_reason:
          type: string
          example: "Order already exists"
        reference:
          type: string
          format: uuid
        orderId:
          type: string
        name:
          type: string
        orderDate:
          type: string
          format: date-time
        amount:
          type: number
        currency:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/ProductResponse'
        cardNumber:
          type: string
          description: May be returned only for 400 invalid-card responses

    # =========================
    # Product Schemas
    # =========================

    ProductBase:
      type: object
      required:
        - productId
        - count
        - spec
      properties:
        productId:
          type: string
          example: 29838-02
        count:
          type: integer
          format: int32
          minimum: 0
          maximum: 100
          example: 2
        spec:
          type: string
          example: xs-83

    ProductRequest:
      allOf:
        - $ref: '#/components/schemas/ProductBase'

    ProductResponse:
      allOf:
        - $ref: '#/components/schemas/ProductBase'
        - type: object
          properties:
            status:
              type: string
              description: Product status (uppercase)
              enum: [PROCESSING, SHIPPED, DELIVERED, FAIL]
              example: SHIPPED
